####

POST http://localhost:4221/login/new/
Content-Type: "application/json"

{
  "username": "NoWayJose",
  "password": "123King"
}

####

POST http://localhost:4221/login
Content-Type: "application/json"

{
  "username": "No1WayJose",
  "password": "123King"
}